---
title: "Function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Importing relevant data sets
library(readr)
getwd()
sales_data = read_csv("data/EXTR_RPSale.csv") #Real Property Sales (.ZIP)
com_building = read_csv("data/EXTR_CommBldg.csv") #Commercial Building (.ZIP)
com_specialuse = read_csv("data/EXTR_CommBldgSection.csv")
com_feature = read_csv("data/EXTR_CommBldgFeature.csv")
condo_complex = read_csv("data/EXTR_CondoComplex.csv")
condo_units = read_csv("data/EXTR_CondoUnit2.csv")
env_restrict = read_csv("data/EXTR_EnvironmentalRestriction_V.csv")
```

```{r}
#Envrionmental Restrictions Data Set
#Cleaning and Factor Type
library(tidyverse)
library(rlang)
test = data.frame(env_restrict)
cleaned_env = test %>%
   mutate(mm_key = paste0(Major, '-', Minor), .before = 1) %>% 
select(-c(Major, Minor)) %>%
select(mm_key,Type,DelineationStudy,PcntAffected)
factor_cols = c("Type")
#Splitting
chunk <- 10000
n <- nrow(cleaned_env)
r <- rep(1:ceiling(n/chunk), each=chunk)[1:n]
d <- split(cleaned_env, r)
#Applying Factor 
d <- lapply(d, function(x){
  x$Type = as.factor(x$Type)
  return(x)
})
cleaned_env = bind_rows(d)

```

```{r}
#Function to take df, and colname
library(glue)

#Function that takes d as dataframe, and the rest of params as colname
test = function(d,c1,...){
colname = c(c1,...)  #stores the colnames in a vector 
print(colname)
for(i in seq_along(colname)){ #Loop through vector of colname
    x = colname[i]
    print(class(x))
  library(rlang)

 # Mutate function using GLUE library for stirng literarls for var name. Also converting the x value to class       type of symbol from charecter so it can be used in mutate function. Nested loop that looks for NA first if true return Real NA, else it continues to next loop to covnert convert
    
    test1 = mutate(d,"{eval(expr({{x}}))}" := ifelse((is.na("{eval(expr({{x}}))}")),NA_real_, ifelse(("{eval(expr({{x}}))}") == "y",1,0))) 
  

  

 
 print(d) 
  
}
 return(test1)

}

test(cleaned_env, "DelineationStudy")
#As you can see the mutate is working on the colomn but setting everything as 0. Also if i try add another colomname. Moved the return function out of the loop and wil now loop through all colnames
```